---
language: node_js
node_js:
- '0.8'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g npm
- npm install -g bower grunt-cli karma
- npm install
- bower install
script: 
- grunt travis
branches:
  only:
    - master
